swagger: '2.0'
info:
  version: '1.0'
  title: my-api
  contact: {}
host: "34.53.36.192:8123"
basePath: "/api"
tags:
  - name: jwks-controller
    x-order: '2147483647'
  - name: main-controller
    x-order: '2147483647'
  - name: user-controller
    x-order: '2147483647'

# 1. 定义安全方案
securityDefinitions:
  your_custom_auth_id:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    # The value below should be unique
    x-google-issuer: "issuer of the token"
    x-google-jwks_uri: "https://us-west1-a-testx-459207:8123/api/auth/.well-known/jwks.json"
    # Optional. Replace YOUR-CLIENT-ID with your client ID
    x-google-audiences: "YOUR-CLIENT-ID"

# 2. 全局安全要求（默认所有接口需要认证）
security:
  - jwt_auth: []

paths:
  "/api/auth/.well-known/jwks.json":
    get:
      tags:
        - jwks-controller
      summary: getJwks
      operationId: getJwksUsingGET
      produces:
        - "*/*"
      # 特别声明此接口不需要认证
      security: []  # 覆盖全局设置
      x-google-backend:
        address: https://us-west1-a-testx-459207:8123/api/auth/.well-known/jwks.json
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
      x-order: '2147483647'
  "/api/health":
    get:
      tags:
        - main-controller
      summary: health
      operationId: healthUsingGET
      produces:
        - "*/*"
      # 特别声明此接口不需要认证
      security: [ ]  # 覆盖全局设置
      x-google-backend:
        address: https://us-west1-a-testx-459207:8123/api/health
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/BaseResponse«string»"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
      x-order: '2147483647'
  "/api/user/delete":
    post:
      tags:
        - user-controller
      summary: deleteUser
      operationId: deleteUserUsingPOST
      consumes:
        - application/json
      produces:
        - "*/*"
      x-google-backend:
        address: https://us-west1-a-testx-459207:8123/api/user/delete
      parameters:
        - in: body
          name: deleteRequest
          description: deleteRequest
          required: true
          schema:
            "$ref": "#/definitions/DeleteRequest"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/BaseResponse«boolean»"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
      x-order: '2147483647'
  "/api/user/get":
    get:
      tags:
        - user-controller
      summary: getUserById
      operationId: getUserByIdUsingGET
      produces:
        - "*/*"
      x-google-backend:
        address: https://us-west1-a-testx-459207:8123/api/user/get
      parameters:
        - name: id
          in: query
          description: id
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/BaseResponse«User»"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
      x-order: '2147483647'
  "/api/user/get/cur":
    get:
      tags:
        - user-controller
      summary: getLoginUser
      operationId: getLoginUserUsingGET
      produces:
        - "*/*"
      x-google-backend:
        address: https://us-west1-a-testx-459207:8123/api/user/get/cur
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/BaseResponse«LoginUserVO»"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
      x-order: '2147483647'
  "/api/user/get/vo":
    get:
      tags:
        - user-controller
      summary: getUserVOById
      operationId: getUserVOByIdUsingGET
      produces:
        - "*/*"
      x-google-backend:
        address: https://us-west1-a-testx-459207:8123/api/user/get/vo
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
        - name: id
          in: query
          description: id
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/BaseResponse«UserVO»"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
      x-order: '2147483647'
  "/api/user/list/page/vo":
    post:
      tags:
        - user-controller
      summary: getUserList
      operationId: getUserListUsingPOST
      consumes:
        - application/json
      produces:
        - "*/*"
      x-google-backend:
        address: https://us-west1-a-testx-459207:8123/api/user/list/page/vo
      parameters:
        - in: body
          name: userQueryRequest
          description: userQueryRequest
          required: true
          schema:
            "$ref": "#/definitions/UserQueryRequest"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/BaseResponse«Page«UserVO»»"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
      x-order: '2147483647'
  "/api/user/login":
    post:
      tags:
        - user-controller
      summary: userLogin
      operationId: userLoginUsingPOST
      consumes:
        - application/json
      produces:
        - "*/*"
      x-google-backend:
        address: https://us-west1-a-testx-459207:8123/api/user/login
      parameters:
        - in: body
          name: userLoginRequest
          description: userLoginRequest
          required: true
          schema:
            "$ref": "#/definitions/UserLoginRequest"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/BaseResponse«LoginUserVO»"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      # 特别声明此接口不需要认证
      security: []  # 覆盖全局设置
      deprecated: false
      x-order: '2147483647'
  "/api/user/logout":
    post:
      tags:
        - user-controller
      summary: userLogout
      operationId: userLogoutUsingPOST
      consumes:
        - application/json
      produces:
        - "*/*"
      x-google-backend:
        address: https://us-west1-a-testx-459207:8123/api/user/logout
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/BaseResponse«boolean»"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
      x-order: '2147483647'
  "/api/user/register":
    post:
      tags:
        - user-controller
      summary: userRegister
      operationId: userRegisterUsingPOST
      consumes:
        - application/json
      produces:
        - "*/*"
      x-google-backend:
        address: https://us-west1-a-testx-459207:8123/api/user/register
      parameters:
        - in: body
          name: userRegisterRequest
          description: userRegisterRequest
          required: true
          schema:
            "$ref": "#/definitions/UserRegisterRequest"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/BaseResponse«long»"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      # 特别声明此接口不需要认证
      security: []  # 覆盖全局设置
      deprecated: false
      x-order: '2147483647'
definitions:
  BaseResponse«LoginUserVO»:
    type: object
    properties:
      code:
        type: integer
        format: int32
      data:
        "$ref": "#/definitions/LoginUserVO"
      message:
        type: string
    title: BaseResponse«LoginUserVO»
  BaseResponse«Page«UserVO»»:
    type: object
    properties:
      code:
        type: integer
        format: int32
      data:
        "$ref": "#/definitions/Page«UserVO»"
      message:
        type: string
    title: BaseResponse«Page«UserVO»»
  BaseResponse«UserVO»:
    type: object
    properties:
      code:
        type: integer
        format: int32
      data:
        "$ref": "#/definitions/UserVO"
      message:
        type: string
    title: BaseResponse«UserVO»
  BaseResponse«User»:
    type: object
    properties:
      code:
        type: integer
        format: int32
      data:
        "$ref": "#/definitions/User"
      message:
        type: string
    title: BaseResponse«User»
  BaseResponse«boolean»:
    type: object
    properties:
      code:
        type: integer
        format: int32
      data:
        type: boolean
      message:
        type: string
    title: BaseResponse«boolean»
  BaseResponse«long»:
    type: object
    properties:
      code:
        type: integer
        format: int32
      data:
        type: integer
        format: int64
      message:
        type: string
    title: BaseResponse«long»
  BaseResponse«string»:
    type: object
    properties:
      code:
        type: integer
        format: int32
      data:
        type: string
      message:
        type: string
    title: BaseResponse«string»
  DeleteRequest:
    type: object
    properties:
      id:
        type: integer
        format: int64
    title: DeleteRequest
  LoginUserVO:
    type: object
    properties:
      createTime:
        type: string
        format: date-time
      editTime:
        type: string
        format: date-time
      id:
        type: integer
        format: int64
      token:
        type: string
      updateTime:
        type: string
        format: date-time
      userAccount:
        type: string
      userAvatar:
        type: string
      userName:
        type: string
      userProfile:
        type: string
      userRole:
        type: string
    title: LoginUserVO
  Page«UserVO»:
    type: object
    properties:
      current:
        type: integer
        format: int64
      pages:
        type: integer
        format: int64
      records:
        type: array
        items:
          "$ref": "#/definitions/UserVO"
      size:
        type: integer
        format: int64
      total:
        type: integer
        format: int64
    title: Page«UserVO»
  User:
    type: object
    properties:
      createTime:
        type: string
        format: date-time
      editTime:
        type: string
        format: date-time
      id:
        type: integer
        format: int64
      isDelete:
        type: integer
        format: int32
      updateTime:
        type: string
        format: date-time
      userAccount:
        type: string
      userAvatar:
        type: string
      userName:
        type: string
      userPassword:
        type: string
      userProfile:
        type: string
      userRole:
        type: string
    title: User
  UserLoginRequest:
    type: object
    properties:
      userAccount:
        type: string
      userPassword:
        type: string
    title: UserLoginRequest
  UserQueryRequest:
    type: object
    properties:
      current:
        type: integer
        format: int32
      id:
        type: integer
        format: int64
      pageSize:
        type: integer
        format: int32
      sortField:
        type: string
      sortOrder:
        type: string
      userAccount:
        type: string
      userName:
        type: string
      userProfile:
        type: string
      userRole:
        type: string
    title: UserQueryRequest
  UserRegisterRequest:
    type: object
    properties:
      checkPassword:
        type: string
      userAccount:
        type: string
      userPassword:
        type: string
    title: UserRegisterRequest
  UserVO:
    type: object
    properties:
      createTime:
        type: string
        format: date-time
      id:
        type: integer
        format: int64
      userAccount:
        type: string
      userAvatar:
        type: string
      userName:
        type: string
      userProfile:
        type: string
      userRole:
        type: string
    title: UserVO
x-openapi:
  x-markdownFiles:
  x-setting:
    language: zh-CN
    enableSwaggerModels: true
    swaggerModelName: Swagger Models
    enableReloadCacheParameter: false
    enableAfterScript: true
    enableDocumentManage: true
    enableVersion: false
    enableRequestCache: true
    enableFilterMultipartApis: false
    enableFilterMultipartApiMethodType: POST
    enableHost: false
    enableHostText: ''
    enableDynamicParameter: false
    enableDebug: true
    enableFooter: true
    enableFooterCustom: false
    footerCustomContent:
    enableSearch: true
    enableOpenApi: true
    enableHomeCustom: false
    homeCustomLocation:
    enableGroup: true
    enableResponseCode: true
