server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: testx
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testx
    username: root
    password: 12345678

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "API Doc"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.it.testx.controller

